var nodemailer = require('nodemailer');

var transporter = nodemailer.createTransport({
  service: 'gmail',
  auth: {
    user: '',  //add your email as a user
    pass: ''   //add password generated by gmail
  }
});

var mailOptions = {
  //add email details
  from: '',
  to: '',
  subject: '',
  text: ''
};

transporter.sendMail(mailOptions, function(error, info){
  if (error) {
    console.log(error);
  } else {
    console.log('Email sent: ' + info.response);
  }
});
